[package]
name = "renet"
version = "0.1.0"
authors = ["Lucas Poffo <lucas.poffo@magrathealabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
async-std = "1.6.2"
serde = "1.0.114"
bincode = "1.3.1"
crc = "1.8.1"
log = "0.4.11"
