[package]
description = "Bevy plugin for the renet crate: Server/Client network library for multiplayer games"
edition = "2021"
keywords = ["gamedev", "networking"]
license = "MIT OR Apache-2.0"
name = "bevy_renet"
readme = "README.md"
repository = "https://github.com/lucaspoffo/renet"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version = "0.7.0", default-features = false}
renet = {path = "../renet", version = "0.0.6"}

[dev-dependencies]
bevy = {version = "0.7.0", default-features = false, features = ["bevy_core_pipeline", "bevy_render", "bevy_pbr", "x11"]}
bincode = "1.3.1"
igd = "0.12.0"
link-conditioner = {git = "https://github.com/Aceeri/link-conditioner"}
my_internet_ip = "0.1.1"
serde = {version = "1.0.117", features = ["derive"]}
