[package]
description = "Server/Client network library for multiplayer games using Renet and UDP"
edition = "2018"
keywords = ["gamedev", "networking"]
license = "MIT OR Apache-2.0"
name = "renet"
readme = "../README.md"
repository = "https://github.com/lucaspoffo/renet"
version = "0.0.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
link-conditioner = {path = "../../link-conditioner"}
log = "0.4.11"
rechannel = {path = "../rechannel", version = "0.0.2"}
renetcode = {path = "../renetcode", version = "0.0.2"}
