[package]
name = "renet"
version = "0.0.5"
description = "Server/Client network library for multiplayer games using Renet and UDP"
keywords = ["gamedev", "networking"]
repository = "https://github.com/lucaspoffo/renet"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rechannel = { path = "../rechannel", version = "0.0.1" }
# renet = "0.0.4"
log = "0.4.11"
